/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_DATA_PB_H_INCLUDED
#define PB_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* simple message that will simply hold a boolean value that determines if we want the LED to toggle on or off */
typedef struct _BlinkData {
    bool has_toggle;
    bool toggle;
} BlinkData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define BlinkData_init_default                   {false, 0}
#define BlinkData_init_zero                      {false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define BlinkData_toggle_tag                     1

/* Struct field encoding specification for nanopb */
#define BlinkData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     toggle,            1)
#define BlinkData_CALLBACK NULL
#define BlinkData_DEFAULT NULL

extern const pb_msgdesc_t BlinkData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define BlinkData_fields &BlinkData_msg

/* Maximum encoded size of messages (where known) */
#define BlinkData_size                           2
#define DATA_PB_H_MAX_SIZE                       BlinkData_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
